project:
  type: website
  output-dir: docs

website:
  title: "ARHU299"
  navbar:
    left:
      - href: pages/syllabus.md
        text: Syllabus
      - href: pages/lecturenotes/index.md
        text: Lecture Notes
      - href: pages/resources.md
        text: Resources

format:
  html:
    theme: 
      dark: darkly
      light: flatly
    css: styles.css
    fontsize: 1.2em
    linestretch: 1.7
    toc: true



